### ISSUE TITLE
Support JavaScript modules

### ISSUE THREAD

**Issue by webfolderio** [Forge-Srl/jjbridge-engine-v8#2]
Hi,

Is it possible use es6 (JavaScript) modules with jjbridge?
Version 0.1.4 throws following exception if import statement is used.

`jjbridge.api.runtime.CompilationException: SyntaxError: Cannot use import statement outside a module`

**Comment by tbossi** [comment]
No, you can't.

jjbridge is meant to provide JS execution capabilities to Java, not to be a full fleged JS environment like a browser or node.js. This means the JS code running inside jjbridge has no access to:

- the file system (thus `require()` and `import` are not available)
- any other [advanced API](https://developer.mozilla.org/en-US/docs/Web/API) usually provided by the browsers and node.js

If you need to manage a small number of JS files you could use the global object `JSRuntime.globalObject()` and multiple `JSRuntime.executeScript()` (without import statements) to share data among those files.

Alternatively, you can try to implement a custom import system injecting a Java implementation for the global `require()` function; but I wouldn't suggest it because can be a quite hard task.

However, if you need a more advanced support for JS in Java, [bionic.js](https://github.com/Forge-Srl/bionic-js) may be what fits your need (and it is built on top of jjbridge).
